### ISSUE TITLE
Documentation spelling error

### ISSUE THREAD

**Issue by akullpp** [rluba/hamjest#11]
In the description of **hasSize**

```
__.assertThat([], __.hasSizeze(__.greaterThan(8))); // Fails
```

Also it would be nice to have an `isEmpty` alias if it's within the scope of Hamjest to focus on readability rather than atomicity.

**Comment by rluba** [comment]
Thank you!

Fixed the typo and implemented `isEmpty` in [v2.11.0](https://github.com/rluba/hamjest/releases/tag/v2.11.0)
