### ISSUE TITLE
Pretty print objects

### ISSUE THREAD

**Issue by akullpp** [rluba/hamjest#13]
Is it possible to pretty print the expected output?

**Comment by rluba** [comment]
Can you give me an example of what you would expect?

**Comment by akullpp** [comment]
Expected: a promise rejected with an object with {something: true}
	     but: was rejected with {"something":false,"a":false,"b":false,"c":false,"d":false,"e": {"a": false,"b": false}}

Now imagine you have an API test with a dozen headers. It gets confusing pretty fast.
