### ISSUE TITLE
`instanceOf` seems not to detect classes extended from Error

### ISSUE THREAD

**Issue by wolframkriesing** [rluba/hamjest#19]
consider the following code
see also discussion https://gist.github.com/wolframkriesing/fa5bfd16e45af3cf5757

```js
import assert from 'assert';
import {assertThat, instanceOf, throws} from 'hamjest';

class MyError extends Error {
  constructor(...args) {
    super(...args);
  }
}
function throwingFunction() {
  throw new MyError();
}
describe('catch my error', () => {
  it('finds error', () => {
    assertThat(throwingFunction, throws(instanceOf(MyError)));
  });
});
```

the output when running the tests

```
  catch my error
    1) finds error


  0 passing (494ms)
  1 failing

  1) catch my error finds error:
     
Expected: a function throwing an instance of MyError
     but: thrown object: {"stack":"Error\n    at MyError.Error (native)\n    at new MyError (test.js:4:7)\n    at throwingFunction (test.js:11:9)\n    at Object.IsFunctionThrowing._.create.describeMismatch (/Users/cain/programming/tmp/hamjest-testing/node_modules/hamjest/lib/matchers/IsFunctionThrowing.js:28:5)\n    at assertThat (/Users/cain/programming/tmp/hamjest-testing/node_modules/hamjest/lib/assertThat.js:28:11)\n    at Context.<anonymous> (test.js:17:5)\n    at callFn (/Users/cain/programming/tmp/hamjest-testing/node_modules/mocha/lib/runnable.js:315:21)\n    at Test.Runnable.run (/Users/cain/programming/tmp/hamjest-testing/node_modules/mocha/lib/runnable.js:308:7)\n    at Runner.runTest (/Users/cain/programming/tmp/hamjest-testing/node_modules/mocha/lib/runner.js:422:10)\n    at /Users/cain/programming/tmp/hamjest-testing/node_modules/mocha/lib/runner.js:533:12\n    at next (/Users/cain/programming/tmp/hamjest-testing/node_modules/mocha/lib/runner.js:342:14)\n    at /Users/cain/programming/tmp/hamjest-testing/node_modules/mocha/lib/runner.js:352:7\n    at next (/Users/cain/programming/tmp/hamjest-testing/node_modules/mocha/lib/runner.js:284:14)\n    at Immediate._onImmediate (/Users/cain/programming/tmp/hamjest-testing/node_modules/mocha/lib/runner.js:320:5)\n    at processImmediate [as _immediateCallback] (timers.js:368:17)"} is a Error
  AssertionError: 
  Expected: a function throwing an instance of MyError
      at Context.<anonymous> (test.js:17:5)

```

I would have expected the test to pass, because `throwingFunction ` does throw `MyError`, but the tests fails :(

**Comment by rluba** [comment]
Which version on Node are you using? Are you using any transpilers, shims, etc.?

**Comment by wolframkriesing** [comment]
i am using node 4.0 and babel 6
i threw it all into https://github.com/wolframkriesing/hamjest-testing
  npm install
and
 npm test
should show the failing test

Saludos, Regards, Gruesse

Wolfram Kriesing
crafting away software

http://es6katas.org
http://jscoderetreat.com

2016-02-25 19:27 GMT+01:00 Raphael Luba <notifications@github.com>:

**Comment by rluba** [comment]
@wolframkriesing OK, Babel explains a lot. Seems like you’ve hit [a known issue](http://stackoverflow.com/a/33877501/110396) with Babel and extending `Error`.

It works perfectly fine in Node 5 **without Babel**:

```JavaScript
		it('should match subinstances of Error', function () {
			class MyError extends Error {
				constructor() {
					super('It’s a MyError');
				}
			}

			sut = __.instanceOf(MyError);

			assertFalse(sut.matches(new Error()));
			assertTrue(sut.matches(new MyError()));
		});
```

```
    instanceOf
      ✓ should throw for non-function arguments
      ✓ should match instances and subinstances
      ✓ should match subinstances of Error
      …
```

**Comment by rluba** [comment]
… but to help you with your actual problem: I usually find it more useful to test for an error’s message than for its type (just like you did in the hamjest-error project):

```JavaScript
   __.assertThat(throwingFunction, __.throws(__.hasProperty('message', __.containsString('the thing I care about')));
```

Because the message or some custom fields are usually the only things that matter for errors (as in "Does it contain the necessary information to help the user figure out what happened?").

**Comment by wolframkriesing** [comment]
Raphael, thanks a lot for finding this and sorry for wasting your time i
could have spent investigating it better.


Saludos, Regards, Gruesse

Wolfram Kriesing
crafting away software

http://es6katas.org
http://jscoderetreat.com

2016-02-26 6:59 GMT+01:00 Raphael Luba <notifications@github.com>:

**Comment by rluba** [comment]
@wolframkriesing Don’t sweat it. [It happens to everyone :-)](https://github.com/nodejs/node/issues/4784)
