### ISSUE TITLE
assertThat(0, equalTo(-0)) fails

### ISSUE THREAD

**Issue by amagee** [rluba/hamjest#23]
This is in contradiction to regular Javascript behaviour where `0 === -0` is `true`. It seems this is happening because we are using an old version of lodash which returns false for `_.isEqual(0, -0)`; this is fixed in the newest release of lodash so upgrading lodash should be sufficient to fix it.

**Comment by rluba** [comment]
Thanks for the report! That's already fixed in the master branch (Version 3.x) of Hamjest.

It’s available as pre-release via `npm install hamjest@next`, but I should really finally publish a 3.0 release.
