### ISSUE TITLE
Plan to make a new release?

### ISSUE THREAD

**Issue by MicahLC** [rluba/hamjest#28]
Hi,

I noticed that the last release of this project was in 2017 and that there have been 25 commits to master since then. Have you considered creating a new release to include those changes?

Cheers,
Micah

**Comment by MicahLC** [comment]
I'm sorry, GitHub had a little `...` thing hiding the newest releases. They are after the one marked `Latest Release`, so I guess maybe just update that?

**Comment by rluba** [comment]
No problem. @MicahLC, the reason is that I haven’t put release notes on any of the newer releases because they mostly contained tiny improvements.
