### ISSUE TITLE
Jasmine html reporter complains about "has no expectations"

### ISSUE THREAD

**Issue by mafo5** [rluba/hamjest#29]
I just created an angular 8 app and with it comes jasmine 3.5.x
After just switching the `expect` statement the default html reporter complains 
- in console: "Spec 'xy' has no expectations"
- in HTML output:  "SPEC HAS NO EXPECTATIONS"
for each `it` where I use the `assertThat`

Tried so far unsuccessfully:
- adding a `return`

Any suggestions to solve this issue?

**Comment by rluba** [comment]
Fixed in 5eb091e
