### ISSUE TITLE
Global functions

### ISSUE THREAD

**Issue by dharkness** [rluba/hamjest#4]
I know, I know. Modules. :)

We don't use any of the module implementations and instead declare our own modules using simple objects. And we don't allow global functions or variables short of the one top-level namespace module.

However, in unit tests I would prefer to read and write

```
assertThat('foo', truthy());
```

instead of

```
__.assertThat('foo', __.truthy());
```

Is there already a mechanism for promoting/copying all of the matcher functions and `assertThat` to global functions. If not, would you entertain a pull request to do it?

We're using JsHamcrest right now, but since we've only just started with JS unit testing it wouldn't be too time-consuming to convert the existing tests. But I'd hate to lose the readability and ease of typing.

**Comment by wolframkriesing** [comment]
just as a side note, this is made easy with ES6, I use it like this https://github.com/cosmowiki/cosmowiki/blob/4c833d115242e02680964c3427e749b69bf79d1e/test/scripts/copy-minified-json-to-directory-spec.js#L3-L8 and it is a pleasure

**Comment by rluba** [comment]
@wolframkriesing Great example, thanks. Although this will get very long and might result in copy & paste boilerplate when you use many matchers. (It already happens in your small example with the unused `assertThat` import.)

**Comment by rluba** [comment]
@dharkness Are you still interested in this feature?

**Comment by dharkness** [comment]
@rluba We're pretty deep into our JS testing at this point, and it's all written with JsHamcrest. Sinon.JS has a mechanism to copy all of the functions of one object to another, so we're covered. You should spend your time on oher priority things and can close this issue if you don't want to keep it open for others/discussion.

**Comment by mattwynne** [comment]
I would just change the docs to say:

```
const { assertThat } = require('hamjest')
```

or for typescript
```
import { assertThat } from 'hamjest'
```

That's pretty idomatic these days.

**Comment by rluba** [comment]
I’ve added an example for TypeScript using destructuring, though I prefer the single import instead of dozens of destructured variables.
